# Site settings
baseURL = "https://alanbraz.com.br"
languageCode = "pt-BR"
theme = "split"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Alan Braz"

[services]
  [services.googleAnalytics]
      ID = "G-8M63DZS7GD"

defaultContentLanguage = 'br'
defaultContentLanguageInSubdir = true

[languages]
  [languages.br]
    title = 'Sobre Alan'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    contentDir = 'content/br'
    weight = 10
    [languages.br.params]
      description = "Engenheiro de Software da área de Pesquisa da IBM Brasil"

  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 200
    title = 'About Alan'
    contentDir = 'content/en'
    [languages.en.params]
      description = "Research Software Engineer at IBM Research Brazil"

[params]
  # Metadata for search engines and social sharing
  author = "Alan Braz"
  shareImage = "images/exame-sm.jpg"
  twitterHandle = "alanbraz"

  # Favicon
  favicon = "favicon.ico"

  [params.custom.css]
    enable = true

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/exame.jpg"
      position = "top center"

    # Video
    # [params.visual.video]
    #   enable = false
    #   mute = true
    #   file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  # [[params.links]]
  #   [params.links.list1]
  #     heading = "Social"

  #     [[params.links.list1.link]]
  #       text = "LinkedIn"
  #       url = "https://www.linkedin.com/in/alanbraz"
  #       new_tab = true

  #     [[params.links.list1.link]]
  #       text = "Twitter"
  #       url = "https://www.twitter.com/alanbraz"
  #       new_tab = true

  #     [[params.links.list1.link]]
  #       text = "Instagram"
  #       url = "https://www.instagram.com/alanbraz"
  #       new_tab = true

  #     [[params.links.list1.link]]
  #       text = "Facebook"
  #       url = "https://www.facebook.com/alanbraz/"
  #       new_tab = true

  # Links List #2
  [[params.links]]
    [params.links.list1]
      heading = "Professional"

      [[params.links.list1.link]]
        text = "Agende sua MentorIA"
        url = "https://www.calendly.com/alanbraz"
        new_tab = true

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/alanbraz"
        new_tab = true

      [[params.links.list1.link]]
        text = "IBM Research"
        url = "https://research.ibm.com/people/alan-braz"
        new_tab = true

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/alanbraz"
        new_tab = true

      [[params.links.list1.link]]
        text = "ResearchGate"
        url = "https://www.researchgate.net/profile/Alan-Braz-2"
        new_tab = true

      [[params.links.list1.link]]
        text = "Google Scholar"
        url = "https://scholar.google.com.br/citations?user=BZujm7MAAAAJ"
        new_tab = true

      # [[params.links.list2.link]]
      #   text = "Credly"
      #   url = "https://www.credly.com/users/alanbraz/badges"
      #   new_tab = true
      

  # Links List #3
  [[params.links]]
    [params.links.list2]
      heading = "Highlights"

      [[params.links.list2.link]]
        text = "Pull reCast podcast"
        url = "http://pullrecast.dev"
        new_tab = true

      [[params.links.list2.link]]
        text = "Comunidade IBM TechXchange Brasil watsonx"
        url = "https://ibm.biz/watsonx-br"
        new_tab = true

      [[params.links.list2.link]]
        text = "Aprenda IA Generativa com IBM watsonx.ai na prática"
        url = "https://www.youtube.com/watch?v=jzPjIUhNXkM"
        new_tab = true

      [[params.links.list2.link]]
        text = "AIMMX project"
        url = "https://github.com/IBM/AIMMX"
        new_tab = true

  [[params.links]]
    [params.links.list3]
      heading = "Talks"

      
      [[params.links.list3.link]]
        text = "HackTown 2024"
        url = "https://link.pullrecast.dev/hacktown24"
        new_tab = true
        
      [[params.links.list3.link]]
        text = "IA Sob Controle podcast #42"
        url = "https://www.iasobcontrole.tech/42-novos-modelos-de-embedding-da-openai-deepfake-do-biden-ia-na-ibm/"
        new_tab = true

      [[params.links.list3.link]]
        text = "Entrevista IA JP News Campians"
        url = "https://www.youtube.com/watch?v=Cbixa3LSXCk"
        new_tab = true

      [[params.links.list3.link]]
        text = "Seminário Internacional Human AI"
        url = "https://www.youtube.com/watch?v=hOivpEPPIuE&t=3656s"
        new_tab = true

      [[params.links.list3.link]]
        text = "CM Summit - TLC-BR Comunidade Técnica da IBM"
        url = "https://www.youtube.com/watch?v=EBis9aTsHio&t=33740s"
        new_tab = true

      # [[params.links.list3.link]]
      #   text = "InnerSource slides"
      #   url = "https://alanbraz.com.br/innersource-tdc/slides.pdf"
      #   new_tab = true

      # [[params.links.list3.link]]
      #   text = "Old blog"
      #   url = "http://alanbraz.wordpress.com/"
      #   new_tab = true 

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
