# Site settings
languageCode = "en-US"
title = "About Alan"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-3KSTQMETGG"

# Copyright
copyright = "&copy;2022 Alan Braz"

[params]

  # Metadata for search engines and social sharing
  author = "Alan Braz"
  description = "Research Research Engineer at IBM Research Brazil"
  shareImage = "images/alan.jpg"
  twitterHandle = "alanbraz"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/alan.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/alanbraz"
        new_tab = true

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/alanbraz"
        new_tab = true

      [[params.links.list1.link]]
        text = "Credly"
        url = "https://www.credly.com/users/alanbraz/badges"


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://www.twitter.com/alanbraz"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/alanbraz"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/alanbraz/"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Highlights"

      [[params.links.list3.link]]
        text = "InnerSource"
        url = "innersource.pdf"

      [[params.links.list3.link]]
        text = "Pull reCast"
        url = "http://pullrecast.dev"

      [[params.links.list3.link]]
        text = "AIMMX"
        url = "https://github.com/IBM/AIMMX"

      [[params.links.list3.link]]
        text = "Old blog"
        url = "http://alanbraz.wordpress.com/"
        
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
